MODEL:
  NAME: 'resnet50'
  IMAGENET_PRETRAINED: 'yes'
  PRETRAIN_PATH: ''
  RESUME_PATH: ''
  METRIC_LOSS_TYPE: 'softmax'
  LABEL_SMOOTH: False




INPUT:
  DATASET: 'cub_200_2011'
  SIZE_RESIZE: 510
  SIZE_TRAIN: 384
  SIZE_TEST: 384

  PROB: 0.5
  RE_PROB: 0.0
  PADDING: 10
  ROOT_DIR: './../../dataset'
  NUM_INSTANCE: 1
  NUM_WORKERS: 1
  TRAIN_BATCH: 10
  TEST_BATCH: 10

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 300
  BASE_LR: 0.00035

  CLUSTER_MARGIN: 0.3
  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 80

  STEPS: [ 50, 80 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 20
  WARMUP_METHOD: 'linear'

  LOG_PERIOD: 20
  EVAL_PERIOD: 1

TEST:

  WEIGHT: ''


OUTPUT_DIR: "../output/Fine-grained-baseline/resnet50"


